---
# tasks file for ven-control
- name: "Check if VEN package exist"
  block:
    - name: "Initial for SUSE Linux Family check"
      command: hostname
      register: package_check
      when: ansible_facts['distribution'] == "SLES"
    - assert:
        that: ansible_facts['distribution'] == "SLES" and (
          ansible_distribution_major_version == "15" or
          ansible_distribution_major_version == "12" or (
          ansible_distribution_major_version == "11" and (
            ansible_distribution_version == "11.3" or
            ansible_distribution_version == "11.4"))
          )
        fail_msg: OS version is not supported!
        success_msg: OS version is supported
      when: ansible_facts['distribution'] == "SLES"
    - include: sles_ven_package.yml

    - name: "Initial for RedHat/CentOS Linux Family check"
      command: hostname
      register: package_check
      when: ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"
    - assert:
        that: (ansible_facts['distribution'] == "RedHat" or
          ansible_facts['distribution'] == "CentOS") and (
          ansible_distribution_major_version == "8" or
          ansible_distribution_major_version == "7" or
          ansible_distribution_major_version == "6")
        fail_msg: OS version is not supported!
        success_msg: OS version is supported
      when: ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"
    - include: redhat_ven_package.yml

    - name: "Initial for Ubuntu Linux Family check"
      command: hostname
      register: package_check
      when: ansible_facts['distribution'] == "Ubuntu"
    - assert:
        that: ansible_facts['distribution'] == "Ubuntu" and
          (ansible_distribution_version == "12.04" or
          ansible_distribution_version == "14.04" or
          ansible_distribution_version == "16.04" or
          ansible_distribution_version == "18.04" or
          ansible_distribution_version == "20.04" or
          ansible_distribution_version == "21.04")
        fail_msg: OS version is not supported!
        success_msg: OS version is supported
      when: ansible_facts['distribution'] == "Ubuntu"
    - include: ubuntu_ven_package.yml

    - name: "Initial for Debian Linux Family check"
      command: hostname
      register: package_check
      when: ansible_facts['distribution'] == "Debian"
    - assert:
        that: ansible_facts['distribution'] == "Debian" and
          (ansible_distribution_release == "jessie" or
          ansible_distribution_release == "wheezy" or
          ansible_distribution_release == "stretch" or
          ansible_distribution_release == "buster")
        fail_msg: OS version is not supported!
        success_msg: OS version is supported
      when: ansible_facts['distribution'] == "Debian"
    - include: debian_ven_package.yml

