---
- name: "Install OS package dependencies for VEN"
  block:
    - name: "Check OS packages dependencies on workloads that going to install VEN"
      command: dpkg-query -l "{{ item }}"
      with_items: "{{ ubuntu_dependency_names }}"
      register: dependency_check
      failed_when: dependency_check.rc > 0
      changed_when: dependency_check.rc > 0

    - name: "Installing {{ ubuntu_dependency_names }}"
      apt:
        name: "{{ ubuntu_dependency_names }}"
        state: present
      register: packages

    - debug:
        msg: 
          - "The following NEW packages have be installed:"
          - "{{ packages.stdout_lines[4] }}"
      when: packages.stdout is defined
  when: ansible_facts['distribution'] == "Ubuntu"
  become: true
